import type { Metadata } from "next";
import { Inter, Shadows_Into_Light } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import RecoilRootWrapper from "@/components/RecoilWrapper";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "next-themes";
import Info from "@/components/Info";

const inter = Inter({ subsets: ["latin"] });

/*
    weight: '400' | Array<'400'>;
    style?: 'normal' | Array<'normal'>;
    display?: Display;
    variable?: T;
    preload?: boolean;
    fallback?: string[];
    adjustFontFallback?: boolean;
    subsets?: Array<'latin'>;
* */
const fontShadow = Shadows_Into_Light({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-shadow",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          fontShadow.variable,
          "min-h-screen bg-background antialiased font-Shadows_Into_Light"
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <RecoilRootWrapper>
            <Header />
            <div className="m-4">{children}</div>
            <Toaster />
          </RecoilRootWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
